[project]
name = "dendonawebsite"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic",
    "asyncpg",
    "dishka",
    "fastapi",
    "mypy>=1.20.0",
    "pydantic-settings",
    "pyjwt",
    "python-multipart",
    "redis",
    "ruff>=0.15.8",
    "sqlalchemy",
    "uvicorn",
]
